enum AuthResultStatus {
  successful,
  emailAlreadyExists,
  wrongPassword,
  invalidEmail,
  userNotFound,
  userDisabled,
  operationNotAllowed,
  tooManyRequests,
  missingIdentifier,
  invalidVerificationCode,
  invalidPhoneNumber,
  verificationCodeExpire,
  undefined,
}
